# AI/ML realated python problems
---


**1.1: Addition of two 2D/3D numpy matrices using for loop**

In [12]:
import numpy as np

def mat_add(mat1: np.ndarray , mat2: np.ndarray):
    
    if mat1.shape != mat2.shape:
        return "Matrix addition isn't possible due to unequal shapes"
    
    result = np.zeros(mat1.shape)
    
    if len(mat1.shape) == 3:
        
        for i in range(mat1.shape[0]):
            for j in range(mat1.shape[1]):
                for k in range(mat1.shape[2]):
                    result[i,j,k] = mat1[i,j,k] + mat2[i,j,k]
    
    elif len(mat1.shape) == 2:
        
        for i in range(mat1.shape[0]):
            for j in range(mat1.shape[1]):
                result[i,j] = mat1[i,j] + mat2[i,j]
    else:
        
        for i in range(mat1.shape[0]):
            result[i] = mat1[i] + mat2[i]

    return result

a = np.random.rand(5,4)
b = np.random.rand(5,4)

c = np.random.rand(5,4,3)
d = np.random.rand(5,4,3)

e = np.random.rand(8)
f = np.random.rand(8)

print()
print("Addition of a two 2d matrice\n")
print(mat_add(a,b))
print()
print("Addition of a two 3d matrice\n")
print(mat_add(c,d))
print()
print("Addition of a two 1d matrice\n ")
print(mat_add(e,f))
print()
print("Addition of a two unequal matrice\n")
print(mat_add(a,c))


    


Addition of a two 2d matrice

[[1.57904236 0.2652171  1.08982227 1.5861536 ]
 [0.75492092 0.59298655 1.530867   1.21165923]
 [1.05256829 1.3812284  0.57797137 0.95016996]
 [1.29683784 0.82458799 0.55174862 0.75439686]
 [1.20653463 1.05552199 0.19858451 1.04695384]]

Addition of a two 3d matrice

[[[0.42011665 0.64177091 1.23409461]
  [1.15263571 1.06718786 0.78918105]
  [0.77112717 0.34608442 1.42826859]
  [1.60700407 1.60516376 1.09785438]]

 [[1.55353125 1.66506332 0.81653945]
  [1.29760011 1.15513188 0.72885189]
  [1.47419714 1.05836063 0.45965362]
  [0.64652943 0.99783094 0.8146532 ]]

 [[0.36514209 0.96484965 0.9052346 ]
  [1.06979688 0.81478934 1.31324816]
  [1.59800438 0.96470054 0.55654818]
  [0.86195839 0.82904209 0.12529057]]

 [[1.13397821 0.89601227 0.75726756]
  [0.92314204 1.99097764 0.71871009]
  [1.56043727 0.3664633  0.4343508 ]
  [0.80473453 0.47160717 0.21372626]]

 [[1.1504793  0.90397102 0.35758532]
  [0.53540481 1.0821654  0.55506606]
  [1.12580958 1.31633314 1.7

---
**1.2: Given the center of a circle, the radius and a random point, find if the point is within the circle, on the circle or outside**

In [24]:
def find_pos_rand_point(circle: tuple = (5,5,10), rand_point: tuple = None):
    
    x,y,r = circle[0], circle[1], circle[2]
    rand_x, rand_y = rand_point[0], rand_point[1]
    
    # find the distance between center and random point using eculedian distance formula
    distance = np.sqrt((x-rand_x)**2 + (y - rand_y)**2)
    
    if distance < r:
        return "inside the circle"
    elif distance == r:
        return "On the circle"
    else:
        return "Outside the circle"


print("Enter the center of the circle(x,y) and radius seprated by spaces, i.e: x y r")
cir = tuple(map(float, input().strip().split(' ')))

print("Enter the random point coordinates i.e: p q")
point = tuple(map(float, input().strip().split(' ')))

print(find_pos_rand_point(cir, point))

Enter the center of the circle(x,y) and radius seprated by spaces, i.e: x y r


 5 5 3


Enter the random point coordinates i.e: p q


 3 2 


Outside the circle


---
**1.3: Given the rectangle diagonal points and a random point find if the random point is inside or outside the rectangle**

In [23]:
def find_pos_rand_point(rect_diag: tuple = (1,3,3,1), rand_point: tuple = None):
    
    diag1_x, diag1_y, diag2_x, diag2_y = rect_diag[0], rect_diag[1], rect_diag[2], rect_diag[3]
    rand_x, rand_y = rand_point[0], rand_point[1]
    
    
    if rand_x > diag1_x and rand_x < diag2_x and rand_y < diag1_y and rand_y > diag2_y:
        return "inside the rectangle"
    elif rand_x == diag1_x or rand_x == diag2_x or rand_y == diag1_y or rand_y == diag2_y:
        return "On the rectangle"
    else:
        return "Outside the rectangle"


print("Enter the top left and bottom right coordinates of a rectangle, i.e: x1 y1 x2 y2")
rect = tuple(map(float, input().strip().split(' ')))

print("Enter the random point coordinates i.e: p q")
point = tuple(map(float, input().strip().split(' ')))

print(find_pos_rand_point(rect, point))

Enter the top left and bottom right coordinates of a rectangle, i.e: x1 y1 x2 y2


 1 3 3 1


Enter the random point coordinates i.e: p q


 4 4 


Outside the rectangle


---